spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # Use update para evitar perda de dados em produção
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
